//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/rjet/shared/CoalMine.java
//

#ifndef _ComRjetSharedCoalMine_H_
#define _ComRjetSharedCoalMine_H_

#import "JreEmulation.h"

@interface ComRjetSharedCoalMine : NSObject {
}

- (NSString *)getStatus;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComRjetSharedCoalMine_init() {}

#endif // _ComRjetSharedCoalMine_H_
