//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/Canary.java
//

#ifndef _Canary_H_
#define _Canary_H_

#import "JreEmulation.h"

@interface Canary : NSObject {
}

- (NSString *)getStatus;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void Canary_init() {}

#endif // _Canary_H_
