//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/developertown/shared/CoalMine.java
//

#include "com/developertown/shared/CoalMine.h"

@implementation ComDevelopertownSharedCoalMine

- (NSString *)getStatus {
  return @"Dark hole";
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getStatus", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComDevelopertownSharedCoalMine = { "CoalMine", "com.developertown.shared", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_ComDevelopertownSharedCoalMine;
}

@end
