//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/developertown/shared/CoalMine.java
//

#ifndef _ComDevelopertownSharedCoalMine_H_
#define _ComDevelopertownSharedCoalMine_H_

#import "JreEmulation.h"

@interface ComDevelopertownSharedCoalMine : NSObject {
}

- (NSString *)getStatus;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComDevelopertownSharedCoalMine_init() {}

#endif // _ComDevelopertownSharedCoalMine_H_
